kind: pipeline
name: default
steps:
- name: test
  image: golang:1.10-alpine
  commands:
    - "go test"
- name: build
  image: golang:1.10-alpine
  environment:
    VERSION: "${DRONE_TAG}"
    COMMIT: "${DRONE_COMMIT_SHA:0:7}"
  commands:
    - "go build -o ./myapp"
- name: publish
  image: plugins/docker
  repo: magalixcorp/k8scicd
  tags: [ "${DRONE_COMMIT_SHA:0:7}" ]
  secrets: [ docker_username, docker_password ]
  
- name: deliver
  image: plugins/ansible:1
  environment:
    K8S_AUTH_KUBECONFIG: 
      from_secret: K8S_AUTH_KUBECONFIG
  settings:
    playbook: .ansible/playbook.yml