pipeline:
  test:
    image: golang:1.10-alpine
    commands:
      - "go test"
  build:
    image: golang:1.10-alpine
    environment:
      VERSION: "${DRONE_TAG}"
      COMMIT: "${DRONE_COMMIT_SHA:0:7}"
    commands:
      - "go build -o ./myapp"
  publish:
    image: plugins/docker
    repo: magalixcorp/k8scicd
    tags: [ "${DRONE_COMMIT_SHA:0:7}" ]
    secrets: [ docker_username, docker_password ]